version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
workflows:
  rdf:
    on: push
    jobs:
      rdflint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 11
        - uses: imas/setup-rdflint@v1
        - name: Run rdflint
          run: rdflint