version: 2
jobs:
  rdflint:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: RDF Lint
          command: |
            .rdflint/check-vocabulary.sh z-sgov
            .rdflint/check-vocabulary.sh v-sgov      
  sgov-validate:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: SGoV Validation
          command: |
            gradle test
      - run:
          name: Save validation results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit           

workflows:
  version: 2
  validate:
    jobs:
      - rdflint
      - sgov-validate
