version: 2
jobs:
  rdflint:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: RDF Lint
          command: |
            .rdflint/check-vocabulary.sh z-sgov
            .rdflint/check-vocabulary.sh v-sgov      
  sgov-validate:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: SGoV Validation
          command: |
            gradle test
      - run:
          name: Save validation results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*" -exec cp {} ~/test-results/junit/ \;
            find . -type f -regex ".*/sgov.trig" -exec cp {} ~/sgov.trig \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - store_artifacts:
          path: ~/sgov.trig
  deploy-to-etl:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Generate TRIG
          command: |
            gradle test
      - run:
          name: Debug
          command: |
            echo $USERNAME
      - run:
          name: Trigger ETL
          command: |
            curl --location --request POST 'https://slovník.gov.cz/etl/resources/executions?pipeline=https://slovník.gov.cz/etl/resources/pipelines/1592398255883' \
            -u $USERNAME:$PASSWORD \
            --form 'input=@./sgov.trig'

workflows:
  version: 2
  validate:
    jobs:
      - rdflint
      - sgov-validate
  build-and-deploy:
    jobs:
      - deploy-to-etl:
          filters:
            branches:
              only: master
