version: 2.1
jobs:
  build:
    docker:
    - image: circleci/openjdk:8
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: run rdflint
        command: |
          RDFLINT_VERSION=0.1.3
          wget https://jitpack.io/com/github/imas/rdflint/$RDFLINT_VERSION/rdflint-$RDFLINT_VERSION.jar
          java -jar rdflint-$RDFLINT_VERSION.jar
