version: 2.1
jobs:
  run:
  build:
    docker:
    - image: circleci/openjdk:8
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: run rdflint
        command: |
          .rdflint/check-vocabulary.sh z-sgov
          .rdflint/check-vocabulary.sh v-sgov
          
